# _config.yml
title: "Jekyll Review System"
baseurl: "" # Set to "/repo-name" if hosted on a subpath
url: "https://rauzidssh.github.io/reviewable_pages/"
repository_url: "https://github.com/RauzhDssh/reviewable_pages"

markdown: kramdown
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge
